#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

run_code_quality_checks() {
  bundle exec rubocop .
}

run_unit_tests() {
  bundle exec rake spec:coverage
}

main() {
  run_code_quality_checks &&
    run_unit_tests
}

main
